version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
      - "33060:33060"
    container_name: mysql-container-compose

 

volumes:
  SonarQube_data:
   driver: local
  SonarQube_extensions:
   driver: local
  SonarQube_logs:
   driver: local
